apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aspectus.fullname" . }}-secret
  labels:
    {{- include "aspectus.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  jwt-private-key-pem: {{ .Values.secrets.jwtPrivateKeyPem | quote }}
  jwt-public-key-pem: {{ .Values.secrets.jwtPublicKeyPem | quote }}
